import "./globals.css";
import "./chat.css";
import "./quizz.css";
import localFont from "next/font/local";

const myFont = localFont({
  src: '../public/fonts/LINESeedSansTH_W_Rg.woff',
  variable: '--font-myfont',
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
